"use client";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useAuth } from "@/contexts/AuthContext";
import { useSummarizeJobAction } from "@/features/api/jobsApi";
import { toastUnknownError } from "@/lib/errors";
import type { Id } from "@qelsa/backend";
import { ChevronUp, Zap } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

export type JobAiSummaryData = {
  role_overview: string;
  key_requirements: string[];
  why_this_role: string;
};

const GRADIENT = "gradient-primary";

export function JobAiSummary({
  jobId,
  summary,
}: {
  jobId: string;
  summary?: JobAiSummaryData | null;
}) {
  const { isAuthenticated, isLoading: authLoading } = useAuth();
  const router = useRouter();
  const generate = useSummarizeJobAction();
  const [expanded, setExpanded] = useState(false);
  const [loading, setLoading] = useState(false);
  const [local, setLocal] = useState<JobAiSummaryData | null>(summary ?? null);
  const data = isAuthenticated ? (summary ?? local) : null;

  const open = async () => {
    if (authLoading) return;
    if (!isAuthenticated) {
      router.push(`/auth?actionType=profile&returnUrl=${encodeURIComponent(`/jobs/${jobId}`)}`);
      return;
    }
    if (data) {
      setExpanded(true);
      return;
    }
    setLoading(true);
    try {
      const result = await generate({ jobId: jobId as Id<"jobs"> });
      setLocal(result);
      setExpanded(true);
    } catch (err) {
      console.error("Job summary failed:", err);
      toastUnknownError(err, "Could not summarize this job. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  if (data && expanded) {
    return (
      <Card className="flex flex-col gap-4 rounded-[20px] border border-white/10 bg-white/[0.03] p-5 lg:p-6">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            <Zap className="size-5 shrink-0 text-neon-purple" />
            <h3 className="text-base font-bold text-white lg:text-lg">AI Job Summary</h3>
          </div>
          <button
            type="button"
            onClick={() => setExpanded(false)}
            className="inline-flex items-center gap-1 text-xs font-semibold text-white/55 hover:text-white"
          >
            Show less
            <ChevronUp className="size-3.5" />
          </button>
        </div>

        <div className="space-y-4 text-sm leading-[22px] text-white/75">
          <section className="space-y-1.5">
            <h4 className="font-semibold text-white">Role Overview</h4>
            <p>{data.role_overview}</p>
          </section>
          {data.key_requirements.length > 0 && (
            <section className="space-y-1.5">
              <h4 className="font-semibold text-white">Key Requirements</h4>
              <ul className="list-disc space-y-1 pl-5">
                {data.key_requirements.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </section>
          )}
          {data.why_this_role && (
            <section className="space-y-1.5">
              <h4 className="font-semibold text-white">Why This Role</h4>
              <p>{data.why_this_role}</p>
            </section>
          )}
        </div>

        <p className="text-xs text-white/40">
          This summary was generated by AI. Review the full description for complete details.
        </p>
      </Card>
    );
  }

  return (
    <Card className="flex flex-col items-start gap-4 rounded-[20px] border border-white/10 bg-white/[0.03] p-5 sm:flex-row sm:items-center sm:justify-between lg:p-6">
      <div className="flex w-full flex-1 flex-col gap-1">
        <h3 className="text-base font-semibold text-white">AI Job Summary</h3>
        <p className="text-sm leading-5 text-white/60">
          A concise overview of the role, responsibilities, requirements, and important details.
        </p>
      </div>
      <Button
        onClick={() => void open()}
        disabled={loading || authLoading}
        className={`h-auto w-full shrink-0 rounded-full px-6 py-2.5 text-sm font-semibold text-white sm:w-auto ${GRADIENT} hover:opacity-90 disabled:opacity-50 shadow-lg shadow-purple-500/20`}
      >
        {loading ? "Summarizing…" : "View summary"}
      </Button>
    </Card>
  );
}
