"use client";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useSummarizeJobAction } from "@/features/api/jobsApi";
import { toastUnknownError } from "@/lib/errors";
import type { Id } from "@qelsa/backend";
import { ChevronDown, ChevronUp, Zap } from "lucide-react";
import { useState } from "react";

export type JobAiSummaryData = {
  role_overview: string;
  key_requirements: string[];
  why_this_role: string;
};

const GRADIENT = "gradient-primary";

export function JobAiSummary({
  jobId,
  summary,
}: {
  jobId: string;
  summary?: JobAiSummaryData | null;
}) {
  const generate = useSummarizeJobAction();
  const [expanded, setExpanded] = useState(Boolean(summary));
  const [loading, setLoading] = useState(false);
  const [local, setLocal] = useState<JobAiSummaryData | null>(summary ?? null);
  const data = summary ?? local;

  const open = async () => {
    if (data) {
      setExpanded(true);
      return;
    }
    setLoading(true);
    try {
      const result = await generate({ jobId: jobId as Id<"jobs"> });
      setLocal(result);
      setExpanded(true);
    } catch (err) {
      console.error("Job summary failed:", err);
      toastUnknownError(err, "Could not summarize this job. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  if (data && expanded) {
    return (
      <Card className="gap-4 rounded-[20px] border-glass-border bg-white/[0.03] p-4 lg:p-6">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            <Zap className="size-5 shrink-0 text-neon-purple" />
            <h3 className="text-lg font-bold text-white lg:text-xl">AI Summary</h3>
          </div>
          <button
            type="button"
            onClick={() => setExpanded(false)}
            className="inline-flex items-center gap-1 text-xs font-semibold text-white/55 hover:text-white"
          >
            Show less
            <ChevronUp className="size-3.5" />
          </button>
        </div>

        <div className="space-y-4 text-sm leading-[22px] text-white/75">
          <section className="space-y-1.5">
            <h4 className="font-semibold text-white">Role Overview</h4>
            <p>{data.role_overview}</p>
          </section>
          {data.key_requirements.length > 0 && (
            <section className="space-y-1.5">
              <h4 className="font-semibold text-white">Key Requirements</h4>
              <ul className="list-disc space-y-1 pl-5">
                {data.key_requirements.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </section>
          )}
          {data.why_this_role && (
            <section className="space-y-1.5">
              <h4 className="font-semibold text-white">Why This Role</h4>
              <p>{data.why_this_role}</p>
            </section>
          )}
        </div>

        <p className="text-xs text-white/40">
          This summary was generated by AI. Review the full description for complete details.
        </p>
      </Card>
    );
  }

  return (
    <Card className="flex-col items-start gap-3 rounded-[20px] border-glass-border bg-white/[0.03] p-4 lg:flex-row lg:items-center lg:gap-4 lg:p-5">
      <div className="flex size-10 shrink-0 items-center justify-center rounded-[20px] border border-glass-border bg-white/[0.04]">
        <Zap className="size-5 text-neon-purple" />
      </div>
      <div className="flex w-full flex-1 flex-col gap-1 lg:w-auto">
        <span className="text-xs font-semibold text-white">AI Summary</span>
        <span className="text-sm leading-5 text-white/70">
          {data
            ? "A short AI overview of this role, requirements, and why it might fit."
            : "Get a quick AI-powered summary of all job requirements, skills, and qualifications."}
        </span>
      </div>
      <Button
        onClick={() => void open()}
        disabled={loading}
        className={`h-auto w-full shrink-0 rounded-full px-4 py-2.5 text-sm font-semibold text-white lg:w-auto ${GRADIENT} hover:opacity-90 disabled:opacity-50`}
      >
        {loading ? "Summarizing…" : data ? (
          <span className="inline-flex items-center gap-1">
            Show summary
            <ChevronDown className="size-3.5" />
          </span>
        ) : (
          "Summarize Requirements"
        )}
      </Button>
    </Card>
  );
}
